# Site settings
title: Daniel Pence - Front-End Developer
email: daniel@danielpence.com
description: The personal blog and portfolio of Daniel Pence, a front-end web developer from Nashville, TN.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.danielpence.com" # the base hostname & protocol for your site
twitter_username: danieldpence
github_username:  danieldpence

# Build settings
markdown: kramdown
permalink: /:title