# Site settings
title: Daniel Pence &mdash; Web Developer
logo-text: DP
email: daniel@danielpence.com
description: Personal blog and portoflio of Daniel Pence, a Web Developer from Nashville, TN.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.danielpence.com" # the base hostname & protocol for your site
twitter_username: danieldpence #enter twitter handle
github_username:  danieldpence #enter github handle
google_font: "Raleway:400,600"
paginate: 3


# Build settings
markdown: kramdown
permalink: /:title
highlighter: pygments

# Default settings
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: Daniel Pence
            layout: "post"
            comments: true
