# Site settings
title: Daniel Pence &mdash; Front End Developer
logo-text: Daniel Pence
email: daniel@danielpence.com
description: Personal Blog of Daniel Pence, a Front End Developer from Nashville, TN.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.danielpence.com" # the base hostname & protocol for your site
twitter_username: danieldpence #enter twitter handle
github_username:  danieldpence #enter github handle
google_font: "Raleway:300,400,600"
paginate: 3


# Build settings
markdown: kramdown
permalink: /:title
highlighter: pygments

# Gems
gems: [jekyll-paginate]

# Default settings
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: Daniel Pence
            layout: "post"
            comments: true
